./herodotus.py ../corp-list-accounts-api --name Listing-Accounts-Api --format html >> request.sh
./herodotus.py ../corp-list-albo-api --name Albo-Api --format html >> request.sh
./herodotus.py ../corp-list-cards-api --name Cards-Api --format html >> request.sh
./herodotus.py ../corp-list-print-api --name Print-Api --format html >> request.sh
./herodotus.py ../corp-list-transactions-api --name Transactions-Api --format html >> request.sh
./herodotus.py ../corp-list-trend-api --name Trend-Api --format html >> request.sh
./herodotus.py ../corp-list-turnovers-api --name Turnovers-Api --format html >> request.sh
./herodotus.py ../corp-rpay-accounts-api --name RPay-Accounts-Api --format html >> request.sh
./herodotus.py ../corp-rpay-catalogs-api --name Catalogs-Api  --format html >> request.sh
./herodotus.py ../corp-rpay-organizations-api --name Organizations-Api --format html >> request.sh
./herodotus.py ../corp-rpay-profiles-api --name Profiles-Api --format html >> request.sh
